

select 
olc.log_id, 
olc.surgery_date, 
olc.room_id,
olc.loc_id,
locat.location_nm,
olc.num_of_panels,
eocap.or_proc_id,
eopc.proc_name, 
epoalc.pat_enc_csn_id,
epoalc.pat_id, 
epoalc.or_link_csn,
epoalc.or_link_inp_id,
ADMIT_DEPARTMENT_ID,
ADMIT_DEPARTMENT,
PRIN_CPT_CODE,
PRIN_ICD10_PROCEDURE_CODE,
PRIN_ICD10_DIAGNOSIS_CODE,
ADMIT_ICD10_DIAGNOSIS_CODE,
ADMIT_PROVIDER_ID,
ATTEND_PROVIDER_ID,
PRINCIPAL_SURGEON_ID,
OR_CASES,
MSDRG_CODE,
MSDRG_CODE_GROUP,
MEDSURG_CODE,
MSDRG_COST_WGT_NBR,
APRDRG_CODE,
APRDRG_ROM,
APRDRG_SOI,
MSMDC,
INSURANCE_PLAN_1,
ADMIT_DT,
DISCHARGE_DT,
COALESCE(A.CHARGE_AMOUNT, 0) + COALESCE(M_PB.CHARGE_AMOUNT, 0) CHARGE_AMOUNT,
COALESCE(A.ESTIMATED_REIMBURSEMENT, 0) + COALESCE(M_PB.ESTIMATED_REIMBURSEMENT, 0) ESTIMATED_REIMBURSEMENT,
COALESCE(A.DIRECT_COST, 0) + COALESCE(M_PB.DIRECT_COST, 0) DIRECT_COST,
COALESCE(A.VAR_INDIRECT_COST, 0) + COALESCE(M_PB.VAR_INDIRECT_COST, 0) VAR_INDIRECT_COST,
COALESCE(A.FIXED_INDIRECT_COST, 0) + COALESCE(M_PB.FIXED_INDIRECT_COST, 0) FIXED_INDIRECT_COST,
--Contribution Margin Calc
COALESCE(A.ESTIMATED_REIMBURSEMENT, 0)  + COALESCE(M_PB.ESTIMATED_REIMBURSEMENT , 0) 
- COALESCE(A.DIRECT_COST, 0)  - COALESCE(M_PB.DIRECT_COST, 0) 
- COALESCE(A.VAR_INDIRECT_COST, 0)  - COALESCE(M_PB.VAR_INDIRECT_COST, 0)  CONTR_MARGIN,
--Contribution Margin Perc
--(COALESCE(A.ESTIMATED_REIMBURSEMENT, 0)  + COALESCE(M_PB.ESTIMATED_REIMBURSEMENT, 0) 
--- COALESCE(A.DIRECT_COST, 0)  - COALESCE(M_PB.DIRECT_COST, 0) 
--- COALESCE(A.VAR_INDIRECT_COST, 0)  - COALESCE(M_PB.VAR_INDIRECT_COST, 0) )/
--(COALESCE(A.ESTIMATED_REIMBURSEMENT, 0)  + COALESCE(M_PB.ESTIMATED_REIMBURSEMENT, 0) ) CONTR_MARGIN_PERC,
--Operating Margin
COALESCE(A.ESTIMATED_REIMBURSEMENT, 0)  + COALESCE(M_PB.ESTIMATED_REIMBURSEMENT, 0) 
- COALESCE(A.DIRECT_COST, 0)  - COALESCE(M_PB.DIRECT_COST, 0) 
- COALESCE(A.VAR_INDIRECT_COST, 0)  - COALESCE(M_PB.VAR_INDIRECT_COST, 0) 
- COALESCE(A.FIXED_INDIRECT_COST, 0)  - COALESCE(M_PB.FIXED_INDIRECT_COST, 0) OP_MARGIN
--,
--Operating Margin Perc
--(COALESCE(A.ESTIMATED_REIMBURSEMENT, 0)  + COALESCE(M_PB.ESTIMATED_REIMBURSEMENT, 0) 
--- COALESCE(A.DIRECT_COST, 0)  - COALESCE(M_PB.DIRECT_COST, 0) 
--- COALESCE(A.VAR_INDIRECT_COST, 0)  - COALESCE(M_PB.VAR_INDIRECT_COST, 0) 
--- COALESCE(A.FIXED_INDIRECT_COST, 0)  - COALESCE(M_PB.FIXED_INDIRECT_COST, 0) )/
--(COALESCE(A.ESTIMATED_REIMBURSEMENT, 0)  + COALESCE(M_PB.ESTIMATED_REIMBURSEMENT, 0) ) OP_MARGIN_PERC

from [Source_UWHealth].EPIC_OR_LOG_CUR olc
join [Source_UWHealth].EPIC_OR_case_ALL_PROC_CUR eocap on olc.log_id = eocap.or_Case_id
join [Source_UWHealth].EPIC_OR_PROC_CUR eopc on eocap.or_proc_id = eopc.or_proc_id
join [Source_UWHealth].EPIC_PAT_OR_ADM_LINK_CUR epoalc on epoalc.log_id = eocap.or_case_id  
join [Modeled_UWHealth].DIM_LOCATION_CUR locat on locat.loc_id = olc.loc_id
join [Mart_UWHealth].[STRATA_COST_ACCOUNT_HB] A on a.pat_enc_csn_id=epoalc.or_link_csn
LEFT JOIN --Joining on Matched PB
(SELECT 
MATCHED_HB_STRATA_ENCOUNTER,
SUM(CHARGE_AMOUNT) CHARGE_AMOUNT,
SUM(ESTIMATED_REIMBURSEMENT) ESTIMATED_REIMBURSEMENT, 
SUM(DIRECT_COST) DIRECT_COST,
SUM(VAR_INDIRECT_COST) VAR_INDIRECT_COST,
SUM(FIXED_INDIRECT_COST) FIXED_INDIRECT_COST
FROM 
[Mart_UWHealth].[STRATA_COST_ACCOUNT_PB]
WHERE MATCHED_HB_STRATA_ENCOUNTER IS NOT NULL
GROUP BY MATCHED_HB_STRATA_ENCOUNTER) M_PB ON A.STRATA_ENCOUNTER_REC_NBR = M_PB.MATCHED_HB_STRATA_ENCOUNTER
INNER JOIN --Subquery to find every Encounter and assign Primary OR Dept
(SELECT B.STRATA_ENCOUNTER_REC_NBR, B.STRATA_DEPARTMENT_CD AS PRIM_OR_DEPT FROM 
(SELECT *, RANK() OVER (PARTITION BY [STRATA_ENCOUNTER_REC_NBR] ORDER BY CHARGES DESC) RANK1
FROM
(SELECT 
      [STRATA_ENCOUNTER_REC_NBR]
	  ,STRATA_DEPARTMENT_CD
	  ,COUNT(DISTINCT [OPTIME_LOG_ID]) OR_CASES
     ,SUM([CHARGE_AMOUNT]) CHARGES
  FROM [Mart_UWHealth].[STRATA_COST_CHARGE_ACTIVITY_HB]
  WHERE 
  [OPTIME_LOG_ID] IS NOT NULL
  --AND [STRATA_DEPARTMENT_CD] IN ('211 - 1060 - 3040280 - 00','211 - 1081 - 3040280 - 00','211 - 1080 - 3040280 - 00','211 - 1080 - 3040290 - 00')
  GROUP BY 
  [STRATA_ENCOUNTER_REC_NBR]
	  ,STRATA_DEPARTMENT_CD
HAVING SUM([CHARGE_AMOUNT]) > 0  --Must have positive charges in OR
) A
) B
WHERE
RANK1 = 1) PRIM_OR ON A.STRATA_ENCOUNTER_REC_NBR = PRIM_OR.STRATA_ENCOUNTER_REC_NBR
where --eocap.or_proc_id = '339628' 
olc.surgery_date >= '01/01/2024'
and eopc.proc_name = 'ARTHROPLASTY, KNEE, TOTAL'
order by surgery_date desc
